version: '3.8'

services:
  eflush-db:
    container_name: eflush-db
    image: postgres:15
    ports:
     - "5656:5432"
    environment:
     POSTGRES_DB: eflush_db
     POSTGRES_USER: eflush
     POSTGRES_PASSWORD: password
    volumes:
      - ./postgresql:/docker-entrypoint-initdb.d/
